language: python
python: 3.4
before_install:
  - wget https://github.com/jedisct1/libsodium/releases/download/1.0.0/libsodium-1.0.0.tar.gz
  - tar xzvf libsodium-1.0.0.tar.gz
  - cd libsodium-1.0.0
  - ./configure && make && make check && sudo make install
  - cd ..
  - sudo ldconfig
install:
  - pip install tox
script:
  - tox -e $TOX_ENV
env:
  - TOX_ENV=py26
  - TOX_ENV=py27
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=py35
  - TOX_ENV=py36
  - TOX_ENV=py37
  - TOX_ENV=pypy
  - TOX_ENV=pypy3
  - TOX_ENV=docs
  - TOX_ENV=flake8
  - TOX_ENV=coverage
after_success: coveralls
